version: 2
updates:
  - package-ecosystem: gradle
    directory: /FtcRobotController/TeamCode
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /FtcRobotController/FtcRobotController
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /FtcRobotController
    schedule:
      interval: weekly
