version: 2
updates:
  - package-ecosystem: gradle
    directory: /TeamCode
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /FtcRobotController
    schedule:
      interval: weekly
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
