name: Android CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant gradlew execution permission
        working-directory: .
        run: chmod +x gradlew

      - name: Test Project with Gradle
        working-directory: .
        run: ./gradlew --stacktrace

      - name: Build Project with Gradle
        working-directory: .
        run: ./gradlew build
