name: Project Build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build with Gradle
        working-directory: ./FtcRobotController
        run: ./gradlew --stacktrace
      - name: Build Project
        working-directory: ./FtcRobotController
        run: ./gradlew build
