name: Android CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Load gradle wrapper
        working-directory: ./FtcRobotController
        run: |
          ./gradlew wrapper --gradle-version 6.5 --distribution-type all

      - name: Build Project with Gradle
        working-directory: ./FtcRobotController
        run: ./gradlew --stacktrace

      - name: Build TeamCode
        working-directory: ./FtcRobotController
        run: ./gradlew :TeamCode build